# Generated by Django 5.0.6 on 2025-03-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_alter_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='from_lead',
            field=models.BooleanField(default=False),
        ),
    ]
