# Generated by Django 5.0.6 on 2025-03-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_customer_from_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('demand_count', models.PositiveIntegerField()),
            ],
        ),
    ]
