# Generated by Django 5.0.6 on 2025-03-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_itemdemand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemDemand',
        ),
    ]
