# Generated by Django 5.0.6 on 2025-03-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_emailgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailGroup',
        ),
    ]
