# Generated by Django 5.0.6 on 2025-03-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_emailmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmember',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crmapp.emailgroup'),
        ),
    ]
