# Generated by Django 5.0.6 on 2025-03-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_alter_emailmember_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailMember',
        ),
    ]
