# Generated by Django 5.0.6 on 2025-03-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_delete_emailmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('lead', 'Lead')], max_length=50)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('quotation', 'Quotation'), ('lost quotation', 'Lost Quotation'), ('customer', 'Customer')], default='lead', max_length=50)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crmapp.emailgroup')),
            ],
        ),
    ]
