# Generated by Django 5.0.6 on 2025-03-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_emailmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmember',
            name='group',
        ),
        migrations.DeleteModel(
            name='EmailGroup',
        ),
        migrations.DeleteModel(
            name='EmailMember',
        ),
    ]
