# Generated by Django 5.0.6 on 2025-03-28 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_remove_emailmember_group_delete_emailgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('purpose', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Lead', 'Lead'), ('Customer', 'Customer')], max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('email_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crmapp.emailgroup')),
            ],
        ),
    ]
